name: Manual Deployment

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}   
      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: <YourSubscriptionId>
          resourceGroupName: <YourResourceGroup>
          template: <path/to/azuredeploy.json>
