name: Manual Deployment

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICE_CREDS }}   
      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: "69c46380-11fc-4928-8685-6308b12a57e2"
          resourceGroupName: ${{TEAM19}}
          template: <path/to/azuredeploy.json>
